---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  annotations:
    flux.weave.works/automated: 'true'
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: 102184001161.dkr.ecr.us-east-1.amazonaws.com/template/samplemicroservice:0.0.24
        ports:
        - containerPort: 80     
