---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  annotations:
    flux.weave.works/automated: 'true'
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/weaveworks/helloworld:master-a000003
        ports:
        - containerPort: 80     
